### ISSUE TITLE
code release 

### ISSUE THREAD

**Issue by abhigoku10** [robot-learning-freiburg/SPINO#1]
@vniclas  thanks for sharing ur which is wonderful can u let us knw when the code shall be released 
THanks in advance

**Comment by vniclas** [comment]
Hi @abhigoku10, we will release the code upon the acceptance of our paper.

**Comment by chengyansheng24** [comment]
@vniclas thanks for sharing,i wanna infer on my own datasets. How can I do that, can u give me some advice,plz!
